
export type Product = {
  id: string;
  name: string;
  category: string;
  district: string;
  price: number;
  cost: number;
  quantity: number;
  measurement: string;
  status: 'active' | 'archived';
  description?: string;
  image: string;
  dataAiHint: string;
};

export type Order = {
  id: string;
  product: string;
  status: 'Pending' | 'Confirmed' | 'On the Way' | 'Delivered';
  date: string;
  amount: number;
}

export type Delivery = {
  id: string;
  orderId: string;
  customerName: string;
  address: string;
  lat: number;
  lon: number;
  status: 'Pending' | 'Out for Delivery' | 'Completed';
  driver: string;
};

export type Parcel = {
  id: string;
  fromStop: string;
  toStop: string;
  senderName: string;
  senderPhone: string;
  receiverName: string;
  receiverPhone: string;
  description: string;
  status: 'Pending' | 'On the Way' | 'Ready for Pickup' | 'Completed';
};


export const categories = ['All', 'Food', 'Clothing', 'Utensils', 'Handicrafts', 'Electronics', 'Farming'];

export const districts = [
    "All Districts", "Achham", "Arghakhanchi", "Baglung", "Baitadi", "Bajhang", "Bajura", "Banke", "Bara", "Bardiya", "Bhaktapur", "Bhojpur", "Chitwan", "Dadeldhura", "Dailekh", "Dang", "Darchula", "Dhading", "Dhankuta", "Dhanusa", "Dolakha", "Dolpa", "Doti", "Gorkha", "Gulmi", "Humla", "Ilam", "Jajarkot", "Jhapa", "Jumla", "Kailali", "Kalikot", "Kanchanpur", "Kapilvastu", "Kaski", "Kathmandu", "Kavrepalanchok", "Khotang", "Lalitpur", "Lamjung", "Mahottari", "Makwanpur", "Manang", "Morang", "Mugu", "Mustang", "Myagdi", "Nawalparasi", "Nuwakot", "Okhaldhunga", "Palpa", "Panchthar", "Parbat", "Parsa", "Pyuthan", "Ramechhap", "Rasuwa", "Rautahat", "Rolpa", "Rukum", "Rupandehi", "Salyan", "Sankhuwasabha", "Saptari", "Sarlahi", "Sindhuli", "Sindhupalchowk", "Siraha", "Solukhumbu", "Sunsari", "Surkhet", "Syangja", "Tanahun", "Taplejung", "Terhathum", "Udayapur"
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Ilam Tea',
    category: 'Food',
    district: 'Ilam',
    price: 800,
    cost: 600,
    quantity: 50,
    measurement: '250g pack',
    status: 'active',
    description: "Savor the authentic taste of the Himalayas with this premium orthodox tea from the rolling hills of Ilam. Known for its delicate floral aroma and muscatel flavor, it's a perfect cup for any time of day.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'tea leaves',
  },
  {
    id: '2',
    name: 'Mustang Apples',
    category: 'Food',
    district: 'Mustang',
    price: 450,
    cost: 300,
    quantity: 0,
    measurement: 'per kg',
    status: 'active',
    description: "Grown in the high-altitude orchards of Mustang, these apples are renowned for their crisp texture and exceptional sweetness. A healthy and delicious treat, perfect for eating fresh or baking.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'red apples',
  },
  {
    id: '3',
    name: 'Palpali Dhaka Topi',
    category: 'Clothing',
    district: 'Palpa',
    price: 700,
    cost: 500,
    quantity: 30,
    measurement: 'piece',
    status: 'active',
    description: "Wear a piece of Nepali heritage with this authentic Dhaka Topi from Palpa. Handwoven with intricate geometric patterns, this traditional cap is a symbol of national pride and cultural identity.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'dhaka topi',
  },
  {
    id: '4',
    name: 'Patan Singing Bowl',
    category: 'Handicrafts',
    district: 'Lalitpur',
    price: 3500,
    cost: 2800,
    quantity: 15,
    measurement: 'piece',
    status: 'active',
    description: "Create a tranquil atmosphere with this handcrafted singing bowl from Patan, the city of fine arts. Used for centuries in meditation and healing, its resonant tones promote relaxation and mindfulness.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'singing bowl',
  },
  {
    id: '5',
    name: 'Jumla Marsi Rice',
    category: 'Food',
    district: 'Jumla',
    price: 300,
    cost: 220,
    quantity: 25,
    measurement: 'per kg',
    status: 'active',
    description: "Cultivated in the highest rice-growing area on Earth, Jumla's Marsi rice is a unique red variety known for its nutty flavor and health benefits. A nutritious and gluten-free choice for your meals.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'red rice',
  },
  {
    id: '6',
    name: 'Bhaktapur Ju Ju Dhau',
    category: 'Food',
    district: 'Bhaktapur',
    price: 250,
    cost: 180,
    quantity: 20,
    measurement: 'clay pot',
    status: 'active',
    description: "Indulge in the 'King of Yogurts,' a rich and creamy delicacy from Bhaktapur. Made from buffalo milk and fermented in a traditional clay pot, its sweet, thick texture is an unforgettable treat.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'yogurt pot',
  },
  {
    id: '7',
    name: 'Bhojpur Khukuri',
    category: 'Handicrafts',
    district: 'Bhojpur',
    price: 2800,
    cost: 2200,
    quantity: 10,
    measurement: 'piece',
    status: 'active',
    description: "Own an authentic piece of Gurkha history with this traditional Khukuri from Bhojpur. Hand-forged by skilled artisans, this iconic curved knife is a powerful tool and a magnificent collector's item.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'khukuri knife',
  },
  {
    id: '8',
    name: 'Dhanusa Mithila Art',
    category: 'Handicrafts',
    district: 'Dhanusa',
    price: 1800,
    cost: 1300,
    quantity: 18,
    measurement: 'piece',
    status: 'active',
    description: "Adorn your walls with a vibrant Mithila painting from the Janakpur region. Characterized by intricate line drawings and vivid colors, these artworks depict mythological and natural themes.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'folk painting',
  },
  {
    id: '9',
    name: 'Chitwan Honey',
    category: 'Food',
    district: 'Chitwan',
    price: 900,
    cost: 700,
    quantity: 35,
    measurement: '500g jar',
    status: 'active',
    description: "Pure, raw honey harvested from the nectar of wildflowers in the plains of Chitwan. This natural sweetener is packed with antioxidants and has a rich, complex flavor profile.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'honey jar',
  },
  {
    id: '10',
    name: 'Kathmandu Pashmina',
    category: 'Clothing',
    district: 'Kathmandu',
    price: 5500,
    cost: 4500,
    quantity: 12,
    measurement: 'piece',
    status: 'active',
    description: "Wrap yourself in luxury with an exquisitely soft Pashmina shawl from the Kathmandu Valley. Made from the fine wool of Himalayan goats, it provides incredible warmth while being feather-light.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'cashmere shawl',
  },
  {
    id: '11',
    name: 'Terhathum Paper',
    category: 'Handicrafts',
    district: 'Terhathum',
    price: 400,
    cost: 250,
    quantity: 100,
    measurement: '10 sheets',
    status: 'active',
    description: "Eco-friendly and durable Lokta paper from the hills of Tehrathum. Traditionally made from the bark of the Daphne plant, it is perfect for journals, crafts, and official documents.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'handmade paper',
  },
  {
    id: '12',
    name: 'Palpa Karuwa',
    category: 'Utensils',
    district: 'Palpa',
    price: 1600,
    cost: 1200,
    quantity: 22,
    measurement: 'piece',
    status: 'active',
    description: "A traditional Nepali water jug made from brass, originating from Palpa. The Karuwa is not only a functional item for storing water but also a beautiful piece of craftsmanship for your home.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'brass jug',
  },
  {
    id: '13',
    name: 'Dolkha Organic Coffee',
    category: 'Food',
    district: 'Dolakha',
    price: 1100,
    cost: 850,
    quantity: 28,
    measurement: '250g pack',
    status: 'active',
    description: "Awaken your senses with aromatic Arabica coffee grown in the mid-hills of Dolkha. This single-origin coffee is known for its smooth body, mild acidity, and hints of citrus and spice.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'coffee beans',
  },
  {
    id: '14',
    name: 'Sunsari Wicker Baskets',
    category: 'Handicrafts',
    district: 'Sunsari',
    price: 950,
    cost: 700,
    quantity: 40,
    measurement: 'set of 3',
    status: 'active',
    description: "Handwoven wicker baskets from the craftsmen of Sunsari. Versatile and sturdy, these baskets are perfect for storage, decoration, or as eco-friendly shopping bags. Available in a set of three sizes.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'wicker basket',
  },
  {
    id: '15',
    name: 'Solukhumbu Yak Cheese',
    category: 'Food',
    district: 'Solukhumbu',
    price: 750,
    cost: 550,
    quantity: 18,
    measurement: '200g block',
    status: 'active',
    description: "A hard, savory cheese made from the milk of yaks grazing in the high pastures of the Everest region. Known locally as 'Chhurpi', it has a unique, tangy flavor and a long shelf life.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'cheese block',
  },
  {
    id: '16',
    name: 'Achham Spices',
    category: 'Food',
    district: 'Achham',
    price: 350,
    cost: 250,
    quantity: 50,
    measurement: '100g pack',
    status: 'active',
    description: "Aromatic blend of traditional spices from the hills of Achham, perfect for authentic Nepali curries.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'spice blend',
  },
  {
    id: '17',
    name: 'Arghakhanchi Coffee',
    category: 'Food',
    district: 'Arghakhanchi',
    price: 1200,
    cost: 900,
    quantity: 30,
    measurement: '250g pack',
    status: 'active',
    description: "Rich, shade-grown Arabica coffee from Arghakhanchi, known for its balanced flavor and smooth finish.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'coffee plantation',
  },
  {
    id: '18',
    name: 'Baglung Allo Scarf',
    category: 'Clothing',
    district: 'Baglung',
    price: 1500,
    cost: 1100,
    quantity: 25,
    measurement: 'piece',
    status: 'active',
    description: "Handwoven scarf made from the fibers of the Himalayan giant nettle (Allo), a sustainable and durable textile.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'woven scarf',
  },
  {
    id: '19',
    name: 'Baitadi Corn Flour',
    category: 'Food',
    district: 'Baitadi',
    price: 150,
    cost: 100,
    quantity: 100,
    measurement: 'per kg',
    status: 'active',
    description: "Stone-ground corn flour (makkai ko pitho) from the terraced farms of Baitadi, ideal for making traditional breads.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'corn flour',
  },
  {
    id: '20',
    name: 'Bajhang Wild Honey',
    category: 'Food',
    district: 'Bajhang',
    price: 1500,
    cost: 1200,
    quantity: 20,
    measurement: '500g jar',
    status: 'active',
    description: "Rare and potent wild honey harvested from the cliffs of Bajhang, known for its medicinal properties.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'wild beehive',
  },
  {
    id: '21',
    name: 'Bajura Buckwheat Flour',
    category: 'Food',
    district: 'Bajura',
    price: 200,
    cost: 150,
    quantity: 80,
    measurement: 'per kg',
    status: 'active',
    description: "Nutritious buckwheat flour (fapar ko pitho) from high-altitude fields in Bajura, perfect for pancakes and noodles.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'buckwheat flour',
  },
  {
    id: '22',
    name: 'Banke Lentils',
    category: 'Food',
    district: 'Banke',
    price: 250,
    cost: 180,
    quantity: 150,
    measurement: 'per kg',
    status: 'active',
    description: "Premium quality black lentils (maas ko daal) from the fertile plains of Banke.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'lentils bowl',
  },
  {
    id: '23',
    name: 'Bara Sugarcane Jaggery',
    category: 'Food',
    district: 'Bara',
    price: 180,
    cost: 120,
    quantity: 200,
    measurement: '500g block',
    status: 'active',
    description: "Sweet, unrefined jaggery (gud) made from fresh sugarcane juice in Bara.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'jaggery blocks',
  },
  {
    id: '24',
    name: 'Bardiya Bananas',
    category: 'Food',
    district: 'Bardiya',
    price: 100,
    cost: 60,
    quantity: 100,
    measurement: 'per dozen',
    status: 'active',
    description: "Sweet and flavorful bananas grown in the tropical climate of Bardiya National Park's buffer zone.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'banana bunch',
  },
  {
    id: '25',
    name: 'Dadeldhura Citrus Fruits',
    category: 'Food',
    district: 'Dadeldhura',
    price: 120,
    cost: 80,
    quantity: 70,
    measurement: 'per kg',
    status: 'active',
    description: "Juicy oranges and citrus fruits from the hills of Dadeldhura, packed with Vitamin C.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'orange fruit',
  },
  {
    id: '26',
    name: 'Dailekh Leather Shoes',
    category: 'Clothing',
    district: 'Dailekh',
    price: 2500,
    cost: 1800,
    quantity: 40,
    measurement: 'pair',
    status: 'active',
    description: "Durable and stylish handmade leather shoes crafted by traditional artisans in Dailekh.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'leather shoes',
  },
  {
    id: '27',
    name: 'Dang Linseed Oil',
    category: 'Food',
    district: 'Dang',
    price: 400,
    cost: 300,
    quantity: 60,
    measurement: '250ml bottle',
    status: 'active',
    description: "Cold-pressed linseed oil (aalas ko tel) from Dang Valley, rich in Omega-3 fatty acids.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'oil bottle',
  },
  {
    id: '28',
    name: 'Darchula Yarsagumba',
    category: 'Farming',
    district: 'Darchula',
    price: 5000,
    cost: 4000,
    quantity: 10,
    measurement: 'per piece',
    status: 'active',
    description: "The prized caterpillar fungus, Yarsagumba, sustainably harvested from the high meadows of Darchula.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'caterpillar fungus',
  },
  {
    id: '29',
    name: 'Dhading Radishes',
    category: 'Food',
    district: 'Dhading',
    price: 80,
    cost: 50,
    quantity: 90,
    measurement: 'per kg',
    status: 'active',
    description: "Crisp and spicy radishes from the fertile riverbanks of Dhading, perfect for pickles (mula ko achar).",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'white radishes',
  },
  {
    id: '30',
    name: 'Dhankuta Oranges',
    category: 'Food',
    district: 'Dhankuta',
    price: 150,
    cost: 100,
    quantity: 120,
    measurement: 'per kg',
    status: 'active',
    description: "Famous Dhankuta oranges, known for their sweet taste and thin skin, a winter delicacy in Nepal.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'orange basket',
  },
  {
    id: '31',
    name: 'Dolpa Shilajit',
    category: 'Farming',
    district: 'Dolpa',
    price: 2000,
    cost: 1500,
    quantity: 15,
    measurement: '10g pack',
    status: 'active',
    description: "Pure Shilajit resin collected from the cliffs of Dolpa, a traditional supplement known for its rejuvenating properties.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'mineral resin',
  },
  {
    id: '32',
    name: 'Doti Castor Oil',
    category: 'Farming',
    district: 'Doti',
    price: 300,
    cost: 220,
    quantity: 40,
    measurement: '100ml bottle',
    status: 'active',
    description: "Organic castor oil from Doti, traditionally used for hair and skin care.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'oil bottle',
  },
  {
    id: '33',
    name: 'Gorkha Oranges',
    category: 'Food',
    district: 'Gorkha',
    price: 130,
    cost: 90,
    quantity: 110,
    measurement: 'per kg',
    status: 'active',
    description: "Sweet and tangy oranges from the historic hills of Gorkha, perfect for fresh juice.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'orange grove',
  },
  {
    id: '34',
    name: 'Gulmi Coffee',
    category: 'Food',
    district: 'Gulmi',
    price: 1250,
    cost: 950,
    quantity: 35,
    measurement: '250g pack',
    status: 'active',
    description: "High-quality Arabica coffee beans from Gulmi, celebrated for their strong aroma and rich flavor profile.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'coffee cup',
  },
  {
    id: '35',
    name: 'Humla Walnuts',
    category: 'Food',
    district: 'Humla',
    price: 800,
    cost: 600,
    quantity: 25,
    measurement: 'per kg',
    status: 'active',
    description: "Organic walnuts from the remote district of Humla, packed with nutrients and flavor.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'walnuts shell',
  },
  {
    id: '36',
    name: 'Jajarkot Ginger',
    category: 'Food',
    district: 'Jajarkot',
    price: 180,
    cost: 130,
    quantity: 70,
    measurement: 'per kg',
    status: 'active',
    description: "Potent and aromatic ginger from Jajarkot, a staple in Nepali kitchens for tea and curries.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'ginger root',
  },
  {
    id: '37',
    name: 'Jhapa Betel Nuts',
    category: 'Food',
    district: 'Jhapa',
    price: 50,
    cost: 30,
    quantity: 300,
    measurement: 'pack of 10',
    status: 'active',
    description: "Fresh betel nuts (supari) from the fertile lands of Jhapa, commonly chewed as a mouth freshener.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'betel nuts',
  },
  {
    id: '38',
    name: 'Kailali Rice',
    category: 'Food',
    district: 'Kailali',
    price: 1500,
    cost: 1200,
    quantity: 200,
    measurement: '25kg bag',
    status: 'active',
    description: "High-quality long-grain rice from Kailali, the rice bowl of western Nepal.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'rice sack',
  },
  {
    id: '39',
    name: 'Kalikot Beans',
    category: 'Food',
    district: 'Kalikot',
    price: 220,
    cost: 170,
    quantity: 60,
    measurement: 'per kg',
    status: 'active',
    description: "Flavorful kidney beans (simi) from Kalikot, perfect for making traditional daal and curries.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'kidney beans',
  },
  {
    id: '40',
    name: 'Kanchanpur Sugar',
    category: 'Food',
    district: 'Kanchanpur',
    price: 100,
    cost: 70,
    quantity: 250,
    measurement: 'per kg',
    status: 'active',
    description: "Fine, processed sugar from the sugarcane fields of Kanchanpur.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'sugar cubes',
  },
  {
    id: '41',
    name: 'Kapilvastu Lassi',
    category: 'Food',
    district: 'Kapilvastu',
    price: 80,
    cost: 50,
    quantity: 150,
    measurement: 'per glass',
    status: 'active',
    description: "Refreshing yogurt-based drink (lassi) from Kapilvastu, the birthplace of Lord Buddha.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'lassi drink',
  },
  {
    id: '42',
    name: 'Kaski Strawberries',
    category: 'Food',
    district: 'Kaski',
    price: 600,
    cost: 450,
    quantity: 40,
    measurement: 'per punnet',
    status: 'active',
    description: "Sweet and juicy strawberries grown in the favorable climate around Pokhara valley.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'strawberry basket',
  },
  {
    id: '43',
    name: 'Kavre Potatoes',
    category: 'Food',
    district: 'Kavrepalanchok',
    price: 90,
    cost: 60,
    quantity: 180,
    measurement: 'per kg',
    status: 'active',
    description: "Versatile red potatoes from Kavre, a major vegetable production hub near Kathmandu.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'red potatoes',
  },
  {
    id: '44',
    name: 'Khotang Turmeric',
    category: 'Food',
    district: 'Khotang',
    price: 250,
    cost: 180,
    quantity: 90,
    measurement: '100g pack',
    status: 'active',
    description: "Vibrant and aromatic turmeric powder from Khotang, known for its strong color and flavor.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'turmeric powder',
  },
  {
    id: '45',
    name: 'Lamjung Ghee',
    category: 'Food',
    district: 'Lamjung',
    price: 1000,
    cost: 800,
    quantity: 50,
    measurement: '500g jar',
    status: 'active',
    description: "Pure, clarified butter (ghee) made from cow's milk in the hills of Lamjung, perfect for cooking and religious ceremonies.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'ghee jar',
  },
  {
    id: '46',
    name: 'Mahottari Fish',
    category: 'Food',
    district: 'Mahottari',
    price: 400,
    cost: 300,
    quantity: 40,
    measurement: 'per kg',
    status: 'active',
    description: "Freshwater fish from the ponds of Mahottari, a local delicacy in the Terai region.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'fresh fish',
  },
  {
    id: '47',
    name: 'Makwanpur Chyau',
    category: 'Food',
    district: 'Makwanpur',
    price: 300,
    cost: 220,
    quantity: 60,
    measurement: 'per kg',
    status: 'active',
    description: "Organic mushrooms (chyau) cultivated in the controlled environments of Makwanpur.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'oyster mushrooms',
  },
  {
    id: '48',
    name: 'Manang Seabuckthorn Juice',
    category: 'Food',
    district: 'Manang',
    price: 500,
    cost: 350,
    quantity: 30,
    measurement: '250ml bottle',
    status: 'active',
    description: "Nutrient-rich juice made from wild seabuckthorn berries found in the high-altitude region of Manang.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'orange juice',
  },
  {
    id: '49',
    name: 'Morang Jute Bags',
    category: 'Handicrafts',
    district: 'Morang',
    price: 400,
    cost: 250,
    quantity: 150,
    measurement: 'piece',
    status: 'active',
    description: "Eco-friendly and strong jute bags produced in the industrial hub of Biratnagar, Morang.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'jute bag',
  },
  {
    id: '50',
    name: 'Mugu Apples',
    category: 'Food',
    district: 'Mugu',
    price: 400,
    cost: 280,
    quantity: 30,
    measurement: 'per kg',
    status: 'active',
    description: "Crisp and juicy apples from the remote and pristine orchards of Mugu.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'green apples',
  },
  {
    id: '51',
    name: 'Myagdi Copper Pot',
    category: 'Utensils',
    district: 'Myagdi',
    price: 2200,
    cost: 1700,
    quantity: 20,
    measurement: 'piece',
    status: 'active',
    description: "Hand-beaten copper pots (gagri) from Myagdi, traditionally used for storing water.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'copper pot',
  },
  {
    id: '52',
    name: 'Nawalparasi Mustard Oil',
    category: 'Food',
    district: 'Nawalparasi',
    price: 350,
    cost: 280,
    quantity: 100,
    measurement: '1L bottle',
    status: 'active',
    description: "Pure mustard oil (tori ko tel) from Nawalparasi, a staple cooking oil in Nepal.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'oil bottle',
  },
  {
    id: '53',
    name: 'Nuwakot Trout Fish',
    category: 'Food',
    district: 'Nuwakot',
    price: 1500,
    cost: 1200,
    quantity: 25,
    measurement: 'per kg',
    status: 'active',
    description: "Fresh rainbow trout farmed in the cold, clear waters of Nuwakot's rivers.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'rainbow trout',
  },
  {
    id: '54',
    name: 'Okhaldhunga Gundruk',
    category: 'Food',
    district: 'Okhaldhunga',
    price: 150,
    cost: 100,
    quantity: 80,
    measurement: '100g pack',
    status: 'active',
    description: "Fermented leafy green vegetable (gundruk), a national dish of Nepal, prepared traditionally in Okhaldhunga.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'dried greens',
  },
  {
    id: '55',
    name: 'Panchthar Cardamom',
    category: 'Food',
    district: 'Panchthar',
    price: 1800,
    cost: 1500,
    quantity: 30,
    measurement: 'per kg',
    status: 'active',
    description: "Large cardamom (alaichi) from Panchthar, a highly prized spice with a strong, smoky aroma.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'cardamom pods',
  },
  {
    id: '56',
    name: 'Parbat Hemp Bag',
    category: 'Clothing',
    district: 'Parbat',
    price: 1800,
    cost: 1400,
    quantity: 40,
    measurement: 'piece',
    status: 'active',
    description: "Durable and eco-friendly bags made from wild hemp, handcrafted by communities in Parbat.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'hemp backpack',
  },
  {
    id: '57',
    name: 'Parsa Rice',
    category: 'Food',
    district: 'Parsa',
    price: 1400,
    cost: 1100,
    quantity: 150,
    measurement: '25kg bag',
    status: 'active',
    description: "Fine grain rice from the fertile plains of Parsa, ideal for daily consumption.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'rice paddy',
  },
  {
    id: '58',
    name: 'Pyuthan Ginger Candy',
    category: 'Food',
    district: 'Pyuthan',
    price: 100,
    cost: 70,
    quantity: 100,
    measurement: '100g pack',
    status: 'active',
    description: "Spicy and sweet ginger candy from Pyuthan, a local remedy for coughs and sore throats.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'ginger candy',
  },
  {
    id: '59',
    name: 'Ramechhap Slate',
    category: 'Handicrafts',
    district: 'Ramechhap',
    price: 500,
    cost: 300,
    quantity: 50,
    measurement: 'piece',
    status: 'active',
    description: "Natural slate stone from the quarries of Ramechhap, used for roofing and paving.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'slate stone',
  },
  {
    id: '60',
    name: 'Rasuwa Red Panda Souvenir',
    category: 'Handicrafts',
    district: 'Rasuwa',
    price: 800,
    cost: 500,
    quantity: 30,
    measurement: 'piece',
    status: 'active',
    description: "Felted wool red panda souvenirs, raising awareness for conservation in Langtang National Park.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'red panda',
  },
  {
    id: '61',
    name: 'Rautahat Mangoes',
    category: 'Food',
    district: 'Rautahat',
    price: 150,
    cost: 100,
    quantity: 120,
    measurement: 'per kg',
    status: 'active',
    description: "Sweet and juicy mangoes from the orchards of Rautahat, a summer favorite.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'mango fruit',
  },
  {
    id: '62',
    name: 'Rolpa Radi Paphi',
    category: 'Clothing',
    district: 'Rolpa',
    price: 3000,
    cost: 2400,
    quantity: 15,
    measurement: 'piece',
    status: 'active',
    description: "Thick woolen blanket (Radi Paphi) made from sheep's wool, traditionally crafted in Rolpa.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'woolen blanket',
  },
  {
    id: '63',
    name: 'Rukum Nettle Powder',
    category: 'Food',
    district: 'Rukum',
    price: 200,
    cost: 150,
    quantity: 50,
    measurement: '100g pack',
    status: 'active',
    description: "Powdered stinging nettle (sisnu ko dhulo), a nutritious superfood from the hills of Rukum.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'green powder',
  },
  {
    id: '64',
    name: 'Rupandehi Curd',
    category: 'Food',
    district: 'Rupandehi',
    price: 120,
    cost: 80,
    quantity: 100,
    measurement: '500g pot',
    status: 'active',
    description: "Fresh and creamy curd (dahi) from the dairy farms of Rupandehi.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'yogurt bowl',
  },
  {
    id: '65',
    name: 'Salyan Ginger',
    category: 'Food',
    district: 'Salyan',
    price: 170,
    cost: 120,
    quantity: 80,
    measurement: 'per kg',
    status: 'active',
    description: "High-quality, spicy ginger from Salyan, known for its strong flavor and medicinal value.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'ginger bunch',
  },
  {
    id: '66',
    name: 'Sankhuwasabha Rudraksha',
    category: 'Handicrafts',
    district: 'Sankhuwasabha',
    price: 1000,
    cost: 700,
    quantity: 40,
    measurement: 'piece',
    status: 'active',
    description: "Authentic Rudraksha beads from the trees of Sankhuwasabha, considered sacred in Hinduism.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'rudraksha beads',
  },
  {
    id: '67',
    name: 'Saptari Makhana',
    category: 'Food',
    district: 'Saptari',
    price: 400,
    cost: 300,
    quantity: 60,
    measurement: '250g pack',
    status: 'active',
    description: "Puffed lotus seeds (makhana) from the wetlands of Saptari, a healthy and crunchy snack.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'lotus seeds',
  },
  {
    id: '68',
    name: 'Sarlahi Tomatoes',
    category: 'Food',
    district: 'Sarlahi',
    price: 80,
    cost: 50,
    quantity: 150,
    measurement: 'per kg',
    status: 'active',
    description: "Juicy, red tomatoes from the fertile lands of Sarlahi, a key ingredient in Nepali cuisine.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'fresh tomatoes',
  },
  {
    id: '69',
    name: 'Sindhuli Junar',
    category: 'Food',
    district: 'Sindhuli',
    price: 200,
    cost: 150,
    quantity: 100,
    measurement: 'per kg',
    status: 'active',
    description: "The famous sweet orange (Junar) of Sindhuli, a juicy and flavorful citrus fruit.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'junar orange',
  },
  {
    id: '70',
    name: 'Sindhupalchowk Helambu Apples',
    category: 'Food',
    district: 'Sindhupalchowk',
    price: 350,
    cost: 250,
    quantity: 50,
    measurement: 'per kg',
    status: 'active',
    description: "Crisp apples from the Helambu region of Sindhupalchowk, known for their refreshing taste.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'apple orchard',
  },
  {
    id: '71',
    name: 'Siraha Litchis',
    category: 'Food',
    district: 'Siraha',
    price: 250,
    cost: 180,
    quantity: 90,
    measurement: 'per kg',
    status: 'active',
    description: "Sweet and succulent litchis from the hot plains of Siraha, a summer delight.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'litchi fruit',
  },
  {
    id: '72',
    name: 'Surkhet Wooden Crafts',
    category: 'Handicrafts',
    district: 'Surkhet',
    price: 1200,
    cost: 800,
    quantity: 30,
    measurement: 'piece',
    status: 'active',
    description: "Intricately carved wooden crafts and souvenirs from the skilled artisans of Surkhet valley.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'wood carving',
  },
  {
    id: '73',
    name: 'Syangja Ginger Ale',
    category: 'Food',
    district: 'Syangja',
    price: 150,
    cost: 100,
    quantity: 100,
    measurement: '300ml bottle',
    status: 'active',
    description: "A refreshing, locally made ginger ale using ginger sourced from the hills of Syangja.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'soda bottle',
  },
  {
    id: '74',
    name: 'Tanahun Bandipure Oranges',
    category: 'Food',
    district: 'Tanahun',
    price: 140,
    cost: 90,
    quantity: 110,
    measurement: 'per kg',
    status: 'active',
    description: "Oranges from Bandipur, Tanahun, known for their unique sweet and tangy flavor profile.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'orange tree',
  },
  {
    id: '75',
    name: 'Taplejung Pathibhara Incense',
    category: 'Handicrafts',
    district: 'Taplejung',
    price: 300,
    cost: 200,
    quantity: 80,
    measurement: 'pack',
    status: 'active',
    description: "Herbal incense sticks made with ingredients from the sacred region of Pathibhara temple in Taplejung.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'incense sticks',
  },
  {
    id: '76',
    name: 'Udayapur Clay Pottery',
    category: 'Utensils',
    district: 'Udayapur',
    price: 600,
    cost: 400,
    quantity: 50,
    measurement: 'piece',
    status: 'active',
    description: "Traditional clay pottery and utensils crafted by the potters of Udayapur.",
    image: 'https://placehold.co/400x300.png',
    dataAiHint: 'clay pot',
  }
];


export const deliveries: Delivery[] = [
    {
        id: "1",
        orderId: "#1004",
        customerName: "Ramesh Thapa",
        address: "Bhedetar, Dhankuta",
        lat: 26.9167,
        lon: 87.3167,
        status: "Out for Delivery",
        driver: "Ram Kumar"
    },
    {
        id: "2",
        orderId: "#1005",
        customerName: "Sunita Rai",
        address: "Chisapani, Ilam",
        lat: 26.9833,
        lon: 87.1333,
        status: "Completed",
        driver: "Ram Kumar"
    },
    {
        id: "3",
        orderId: "#1003",
        customerName: "Gita Gurung",
        address: "Sankhejung, Ilam",
        lat: 27.0194,
        lon: 87.8044,
        status: "Pending",
        driver: "Sita Devi"
    }
];

export const routeStops = [
  { name: "Chisapani Market", lat: 26.9833, lon: 87.1333 },
  { name: "Bhedetar Junction", lat: 26.9167, lon: 87.3167 },
  { name: "Sankhejung Village", lat: 27.0194, lon: 87.8044 },
];

export const parcels: Parcel[] = [
    {
        id: "P1",
        fromStop: "Chisapani Market",
        toStop: "Sankhejung Village",
        senderName: "Bikash",
        senderPhone: "9812345678",
        receiverName: "Srijana",
        receiverPhone: "9887654321",
        description: "Important Documents",
        status: "On the Way"
    },
];

export const initialOrders: Order[] = [
  { id: "#1005", product: "Warm Fleece Jacket", status: "Delivered", date: "2023-06-27", amount: 1500.00 },
  { id: "#1004", product: "Stainless Steel Pot Set", status: "On the Way", date: "2023-06-26", amount: 2500.00 },
  { id: "#1003", product: "Basmati Rice (25kg)", status: "Confirmed", date: "2023-06-25", amount: 3200.00 },
];
