name: Keep Supabase Project Alive

on:
  schedule:
    - cron: '13 2 * * *'   # 02:13 UTC
    - cron: '47 9 * * *'   # 09:47 UTC
    - cron: '22 17 * * *'  # 17:22 UTC
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Random delay 0-5 min
        run: sleep $((RANDOM % 300))

      - name: Ping Supabase ping_dummy table
        id: ping
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
            "https://${{ secrets.SUPABASE_PROJECT_REF }}.supabase.co/rest/v1/ping_dummy?limit=1")
          echo "Ping status: $STATUS"
          echo "status=$STATUS" >> $GITHUB_OUTPUT

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "✅ Supabase Keep-Alive Ping Run at $(date -u)"
          to: "sagarrana@gmail.com"
          from: "GitHub Action <${{ secrets.EMAIL_USERNAME }}>"
          body: |
            Hello Sagar Rana,

            Your Supabase keep-alive GitHub Action just ran successfully.

            Status Code: ${{ steps.ping.outputs.status }}
            Project: ${{ secrets.SUPABASE_PROJECT_REF }}
            Time (UTC): $(date -u)

            Regards,
            Your GitHub Automation Bot
