name: Keep Supabase Database Active

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:         # allows manual trigger

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Send ping to Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          curl -X POST "$SUPABASE_URL/rest/v1/rpc/pg_sleep" \
          -H "apikey: $SUPABASE_ANON_KEY" \
          -H "Authorization: Bearer $SUPABASE_ANON_KEY" || true
