name: Keep Supabase Project Alive

on:
  schedule:
    - cron: '13 2 * * *'   # 02:13 UTC
    - cron: '47 9 * * *'   # 09:47 UTC
    - cron: '22 17 * * *'  # 17:22 UTC
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Random delay 0-5 min
        run: sleep $((RANDOM % 300))

      - name: Ping Supabase ping_dummy table
        run: |
          curl -s -o /dev/null -w "%{http_code}\n" \
            -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
            "https://${{ secrets.SUPABASE_PROJECT_REF }}.supabase.co/rest/v1/ping_dummy?limit=1"
